server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # проксирует /api запросы на бэкенд
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # всё остальное отдаёт index.html для Vue Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}
